services:
  - type: web
    name: sistema-solicitudes-refrigerios
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_ENV
        value: production